export const INTERESTS_LIST = [
  "Comedy", "Singing", "Fitness", "Cooking", "Dancing", "AI", "Gaming", "Travel",
  "Movies", "Photography", "Reading", "Poetry", "Art", "Design", "Coding",
  "Technology", "Startups", "Mental Health", "Spirituality", "Sports",
  "Cricket", "Football", "Basketball", "Cycling", "Yoga", "Fashion", "Beauty",
  "Education", "Books", "Writing", "Blogging", "Finance", "Marketing",
  "Acting", "Languages", "History", "Science", "Nature", "Outdoors", "Pets",
  "Cats", "Dogs", "DIY", "Parenting", "Relationships", "Music", "Anime",
  "K-Pop", "Classical Music", "Investing", "Entrepreneurship", "Theatre",
  "Chess", "Cars", "Motorcycles", "Astronomy", "Space", "Meditation", "UX/UI",
  "Frontend", "Backend", "Cybersecurity", "Blockchain", "Crypto", "Stocks",
  "Productivity", "Leadership", "Public Speaking", "Self Improvement", "Baking",
  "Knitting", "Interior Design", "Architecture", "Economics", "Politics",
  "Climate", "Environment", "Volunteering", "Adventure", "Scuba Diving",
  "Hiking", "Mountains", "Beaches", "Skincare", "Makeup", "Haircare", "Photography Editing",
  "Film Making", "Short Films", "Memes", "Dark Humor", "Storytelling",
  "Voice Acting", "Languages Learning", "Tutoring", "Career Advice", "Podcasts",
  "Philosophy", "Mindfulness", "Astrology", "Tarot", "Science Fiction", "Horror",
  "Thriller", "Romance", "Pop Culture", "Trends", "Reels", "Vlogs",
  "Live Streaming", "Motivation", "Quotes", "Animals", "Bird Watching",
  "Camping", "Tech Reviews", "Gadgets", "Smartphones", "AI Tools", "ReactJS",
  "NodeJS", "MongoDB", "DevOps", "Docker", "GitHub", "VSCode", "Linux",
  "Windows", "Mac", "Typing", "Resume Building", "Freelancing", "Remote Work",
  "Work From Home", "Job Search", "Internships", "College Life", "Study Tips",
  "Scholarships", "Exams", "CBSE", "IIT JEE", "NEET", "UPSC", "SSC", "Banking",
  "CSE", "ECE", "IT", "BCA", "MCA", "Engineering", "MBA", "CAT", "GMAT", "GRE",
  "IELTS", "TOEFL", "Python", "Java", "C++", "C", "JavaScript", "Django",
  "Flask", "Spring Boot", "Flutter", "Android", "iOS", "Swift", "Kotlin",
  "Unity", "Unreal", "Game Dev", "AR/VR", "3D Modeling", "Figma", "Canva",
  "Illustrator", "Photoshop", "Premiere Pro", "After Effects", "Web Design"
];
